# Generated by Django 5.2.7 on 2025-11-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
