# Generated by Django 5.2.7 on 2025-11-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertoken_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='dc_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
