# Generated by Django 5.2.7 on 2025-10-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='data_venciment',
            new_name='data_vencimento',
        ),
        migrations.AddField(
            model_name='atualizacaoconta',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atualizacaoconta',
            name='status',
            field=models.CharField(choices=[('p', 'Pendente'), ('c', 'Cancelada'), ('f', 'Finalizada')], default='p', max_length=1),
        ),
    ]
