# Generated by Django 5.2.7 on 2025-10-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaoconta',
            name='status',
            field=models.CharField(choices=[('p', 'Pendente'), ('c', 'Cancelada'), ('f', 'Finalizada'), ('v', 'Vencida')], default='p', max_length=1),
        ),
    ]
