# Generated by Django 5.2.7 on 2025-10-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_atualizacaoconta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaoconta',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
