# Generated by Django 5.2.7 on 2025-10-28 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_conta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
