# Generated by Django 5.2.7 on 2025-10-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_conta_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='atualizacaoconta',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
