# Generated by Django 5.2.7 on 2025-10-29 00:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fornecedor_conta_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
