# Generated by Django 5.2.7 on 2025-10-29 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_fornecedor_cnpj_alter_fornecedor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
    ]
