# Generated by Django 5.2.7 on 2025-11-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_conta_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='atualizacaoconta',
            name='pagamento',
            field=models.CharField(blank=True, choices=[('d', 'Dinheiro/Espécie'), ('p', 'Pix'), ('c', 'Cartão de Crédito'), ('d', 'Cartão de Débito'), ('t', 'Transferência'), ('o', 'Outros')], default=None, max_length=1, null=True),
        ),
    ]
