# Generated by Django 5.2.7 on 2025-11-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_atualizacaoconta_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaoconta',
            name='pagamento',
            field=models.CharField(blank=True, choices=[('d', 'Dinheiro/Espécie'), ('p', 'Pix'), ('c', 'Cartão de Crédito'), ('b', 'Cartão de Débito'), ('t', 'Transferência'), ('o', 'Outros')], default=None, max_length=1, null=True),
        ),
    ]
